{
 "title": "NovaMarket - App",
 "tags": [ "novamarket" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memoria residente (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nova_process_resident_memory_bytes",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "CPU acumulada (segundos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(nova_process_cpu_seconds_total[1m])",
     "legendFormat": "cpu/s"
    }
   ]
  },
  {
   "title": "Peticiones HTTP por ruta (rate 1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (route,status) (rate(nova_http_requests_total[1m]))",
     "legendFormat": "{{route}} {{status}}"
    }
   ]
  },
  {
   "title": "Operaciones de negocio (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (operation,result) (nova_business_operations_total)",
     "legendFormat": "{{operation}} {{result}}"
    }
   ]
  },
  {
   "title": "Uptime del proceso (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "time() - nova_process_start_time_seconds"
    }
   ]
  }
 ]
}